version: '3'

services:
  be:
    build:
      context: ./be
    command: gunicorn config.wsgi --bind 0.0.0.0:8000

  fe:
    build:
      context: ./fe
    volumes:
      - react_build:/react/dist

  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react
    depends_on:
      - be
      - fe

volumes:
  react_build:

